language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libx11-dev
  - sudo add-apt-repository -y ppa:gijzelaar/cuda
  - sudo add-apt-repository -y ppa:gijzelaar/opencv2.3
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.7
  - sudo apt-get -qq install libcv-dev
  - export CXX=g++-4.7
  - export CC=gcc-4.7
script:
  - mkdir build
  - cd build
  - cmake ../
  - make -j 4
