language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libx11-dev
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install

script:
  - mkdir build
  - cd build
  - cmake ../
  - make -j 4
