language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libx11-dev libcv-dev libopencv-contrib-dev libopencv-gpu-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make -j 4
